[package]
name = "lsr"
version = "0.1.0"
edition = "2021"
[[bin]]
name = "lsr"  # Nome personalizado para o executável
path = "src/main.rs"         # Caminho para o arquivo principal do código fonte


[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
